[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
remappings = [
    '@superfluid-finance/ethereum-contracts=lib/superfluid-protocol-monorepo/packages/ethereum-contracts',
    '@superfluid-finance/solidity-semantic-money=lib/superfluid-protocol-monorepo/packages/solidity-semantic-money',
    '@openzeppelin-v5/contracts=lib/openzeppelin-contracts-v5/contracts',
    '@superfluid-finance/automation-contracts/=lib/superfluid-protocol-monorepo/packages/automation-contracts/',
]
